version: '3.3'

services:
    localstack_sqs:
        image: localstack/localstack:0.9.4
        environment:
            - SERVICES=sqs
        ports:
            - "4576:4576"
    app_ab:
        build: .
        depends_on:
            - localstack_sqs
        entrypoint: /bin/bash
        command: "gradlew run --args 'queue_A queue_B'"
        restart: unless-stopped
        links:
            - localstack_sqs 
    app_ba:
        build: .
        depends_on:
            - localstack_sqs
        entrypoint: /bin/bash
        command: "gradlew run --args 'queue_B queue_A'"
        restart: unless-stopped
        links:
            - localstack_sqs
